import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./component/footer";
import Navbar from "./component/navbar";
import ScrollToTop from "./component/ScrollToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}> {/* ✅ Moved here */}
      <body>
  <Navbar /> {/* Navbar already includes Avion category bar; removed duplicate Header */}
        {children}
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}

